#!/bin/bash
#
# Ncycle     = Number Of Cycles
# Ninit      = Number Of Equilibration Cycles (Check Value!)
# Npart      = Number Of Particles
# MolFrac    = Mole Fraction of Particles in Reservoir (for Mu)
# Linit      = Read Old Configuration From Disk ?
#              .True. Make New Initial Configuration
#              .False. Read Initial Configuration From File Coordold
# Temp       = Temperature
# Iensemble  = Which Ensemble Do We Simulate ?
#              1 = Nvt Ensmeble
#              2 = Npt Ensemble
#              3 = Muvt Ensemble (Specify The Fugacity Press)
#              4 = Gibbs Ensemble
#              5 = Reaction Ensemble
# Pdisp      = Fraction Displacements
# Pswap      = Fraction Particle Swaps
# Pvol       = Fraction Volume Changes
# Prxn       = Fraction Reaction Moves
# Potential  = 0 for Hard Sphere, 1 for Lennard-Jones w/ Cut and Shift,
#              2 for Lennard-Jones w/ Cut and Tail Correction
# Nrxn       = Number Of Reactions (defined at bottom)
# Ntype      = Number Of Types (parameters below must be consistent)
# Deltax     = Maximum Particle Displacement
# Deltav     = Maximum Volume Change
# Press/Fuga = Pressure (Npt Ensemble) Or Fugacity (Muvt Ensemble)
#              For Muvt Ensemble: Fuga=Exp[Beta*Mu]/Beta
# Nprint     = Frequency Of Trajectory Output
# Box        = Size Of Each Simulation Box
# Nparts,MolFrac       = Number Of Each Type and IG Mol Fraction
# Eps,Sig              = LJ Parameter Definitions
# Nreactants,Nproducts = Number Of Reactants and Products for Each Rxn
# Reactions,Stoich     = Specify Reactant/Product Types and Stoichiometry
#
# Output
#
# Coordnew    = Final Coordinates
# Radial      = Radial Distribution Function
# Traject.xyz = Trajectory (Can Be Visualized Using vmd)
# Results     = Instantaneous Values Of:
#               For Gibbs Ensemble:
#               Column 1: Cycle Number
#               Column 2: Density Box 1
#               Column 3: Density Box 2
#               Column 4: Energy Per Particle Box 1
#               Column 5: Energy Per Particle Box 2
#               Column 6: Pressure Box 1
#               Column 7: Pressure Box 2
#               For NVT, NPT, MuVT Ensemble
#               Column 1: Cycle Number
#               Column 2: Density
#               Column 3: Energy Per Particle
#               Column 4: Pressure
# Rho         = Probability Distribution for A Certain Density

# 1   1
# 1   2
# 1   3
# 1   4
# 2   2
# 2   3
# 2   4
# 3   3
# 3   4
# 4   4

cat > Input <<endofdata1
Ncycle   Ninit   Linit   Temp   Iensemble
10000    200    .True.   0.7    5
Pdisp    Pswap   Pvol    Prxn   Potential
1        1       0.03    5      1
Nrxn     Ntype
1        2
Deltax   Deltav  Press/Fuga
0.5      40       1
Nprint
100
Box(1)   Box(2)
10       10
Nparts,MolFrac (Ntype)
160 1
100 1
Eps,Sig (Ntype*(Ntype+1)/2)
1 1
0.75 1
1 1
Nreactants,Nproducts (Nrxn)
1 1
Reactions,Stoich (Nrxn heading) (Nproducts + Nreactants)
Rxn 1
1 2
2 1
endofdata1

time ../source/a.out

